{% set name = "pyccl" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be8bb0f2bd1e56382371f06e7926f1821dc8d6250bbac37c5d0fdc4b6c421bb1
  patches:
    - remove_setuptools_build.patch

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools_scm
    - fftw
    - gsl
    - numpy
    - swig
    - libcblas
    - llvm-openmp  # [osx]
  run:
    - python
    - camb >=1
    - pyyaml
    - fftw  # apparently FFTW doesn't have a run export
    - {{ pin_compatible('numpy') }}
    - llvm-openmp  # [osx]

test:
  imports:
    - pyccl

about:
  home: https://github.com/LSSTDESC/CCL
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'DESC Core Cosmology Library: cosmology routines with validated numerical accuracy'

extra:
  recipe-maintainers:
    - beckermr
