{% set name = "pyccl" %}
{% set version = "2.0.0rc3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git-url: https://github.com/hsinfan1996/CCL.git

build:
  number: 2
  skip: True  # [win]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - fftw
    - gsl
    - numpy
    - swig
    - libcblas
    - llvm-openmp  # [osx]
  run:
    - python
    - pycamb
    - pyyaml
    - fftw  # apparently FFTW doesn't have a run export
    - {{ pin_compatible('numpy') }}
    - llvm-openmp  # [osx]

test:
  imports:
    - pyccl

about:
  home: https://github.com/LSSTDESC/CCL
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'DESC Core Cosmology Library: cosmology routines with validated numerical accuracy'

extra:
  recipe-maintainers:
    - beckermr
