{% set name = "pyccl" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9da527e6bebd6241190c8988054fb23eeed9874aef14bbdc5abe2076086ed19c
  patches:
    - remove_setuptools_build.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools_scm
    - fftw
    - gsl
    - numpy
    - swig
    - libcblas
    - llvm-openmp  # [osx]
  run:
    - python
    - camb >=1
    - pyyaml
    - fftw  # apparently FFTW doesn't have a run export
    - {{ pin_compatible('numpy') }}
    - llvm-openmp  # [osx]
    - matplotlib-base
    - scipy
    - fast-pt

test:
  imports:
    - pyccl

about:
  home: https://github.com/LSSTDESC/CCL
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'DESC Core Cosmology Library: cosmology routines with validated numerical accuracy'

extra:
  recipe-maintainers:
    - beckermr
