{% set name = "pyccl" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01e2959bf3e1c60539acc75dda7c1195733944cebe4d4373bb77a8c7269d3583
  patches:
    - remove_setuptools_build.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake <3.24
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - swig
  host:
    - python
    - pip
    - setuptools_scm
    - fftw
    - gsl
    - numpy
    - libcblas
  run:
    - python
    - camb >=1
    - pyyaml
    - fftw  # apparently FFTW doesn't have a run export
    - {{ pin_compatible('numpy') }}
    - matplotlib-base
    - scipy
    - fast-pt

test:
  imports:
    - pyccl

about:
  home: https://github.com/LSSTDESC/CCL
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'DESC Core Cosmology Library: cosmology routines with validated numerical accuracy'

extra:
  recipe-maintainers:
    - beckermr
