{% set name = "pyccl" %}
{% set version = "2.0.0rc3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/CCL/archive/v{{ version }}.tar.gz
  sha256: d1e15826b2b58b32c9e3531c2818caaf67fd7810f2ebde45b4fcd1594c4e1221
  patches:
    - remove_setuptools_scm.patch

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - cmake >=3.2
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - fftw >=3.1
    - gsl >=2.1
    - numpy
    - swig
    - libcblas
    - llvm-openmp  # [osx]
  run:
    - python
    - pycamb
    - pyyaml
    - fftw >=3.1  # apparently FFTW doesn't have a run export
    - {{ pin_compatible('numpy') }}
    - llvm-openmp  # [osx]

test:
  imports:
    - pyccl

about:
  home: https://github.com/LSSTDESC/CCL
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'DESC Core Cosmology Library: cosmology routines with validated numerical accuracy'

extra:
  recipe-maintainers:
    - beckermr
